### ISSUE TITLE
1.7.0 Release

### ISSUE THREAD

**Issue by whyman** [gerbera/gerbera#1108]
Reminder to a 1.7.0 release in January.

Please add issues to the 1.7.0 milestone if blockers.

**Comment by whyman** [comment]
@KarlStraussberger would you mind putting together some text for the release notes/changelog around the config stuff?

I guess we will need a something on adding resources too?

And anything else you think is worth including.

**Comment by KarlStraussberger** [comment]
I did my very best to make it understandable for our users. Feel free to amend, remove and edit.

---

Code changes
- chose to build with libnupnp instead of libupnp
- make use of modern C++17 features
- internal refactoring and code improvement
- many bug fixes

UPnP changes
- container images also on containers without files
- subtitle resource on SAMSUNG clients

Web UI changes
- display thumbnails, album art and container images (database view)
- set additional import options for directories on filesystem page (tweaks)
- page to edit configuration (most of it), your settings are stored in the database

Configuration changes (amoungst many more)
- charset can be specific to import library (section: import/library-options), e.g. if your pictures use different encoding than your music
- resource configuration can be used for container images (section: import/resources): define image name filters and strategy for container hierarchy

Database changes
- additional metadata stored from import scan
- modification time for autoscan directories now reflects sub directories and reduces startup footprint
- container images are stored as resources so browsing can return them directly 

In order to benefit from all these improvements it is recommended to clear your database and rescan your media library.

**Comment by whyman** [comment]
Got other commitments so will be delayed, but before March!
