### ISSUE TITLE
[Question] HEVC decoding on live for old TVs

### ISSUE THREAD

**Issue by Hospes** [gerbera/gerbera#1201]
Hey guys, you did great job with Gerbera, thank you !
I have LG Smart tv that can play media files through default player. Natively it doesn't support HEVC files.
Is there any possibility to somehow decode on the fly on server side HEVC file and transform it to H.264 ? So TV can play it as it was H.264 file ?

**Comment by KarlStraussberger** [comment]
You may have a look into [Transcoding](https://docs.gerbera.io/en/latest/config-transcode.html). Needs a bit of resources on your media server.

The main issue with (at leas my 2010) LG is that you need to produce the exact aspect ratio for the screen to scale to full screen otherwise the movie is sitting in the middle of the screen in its original size.

**Comment by Hospes** [comment]
@KarlStraussberger thank you.
Can you hep me understand how can I set proper profile for transcoding that will detect .mkv files that encoded with H.264 and H.265 ?
This would be a bit wasting of resource if my server will transcode every mkv file wtihout detecting if its encoded with H.265.
Is there any possbility to do it?

**Comment by KarlStraussberger** [comment]
I don't see a way to do this. There is no such feature as to filter by special properties. Transcoding only filters by mimetype. So, if you're able to figure out some mime type voodoo it can be done.

You'll buy a new TV set before we're done with that 🤣

**Comment by whyman** [comment]
I think the ffmpeg handler will extract the type of the main stream and store it with the resource, but that still doesnt help as transcoding only uses the mime type as mentioned above.

So it would need to be a patch to allow using that information in a transcoding profile, which is a sensible addition for a friendly contributor out there!

**Comment by welljsjs** [comment]
> it would need to be a patch to allow using that information in a transcoding profile

I'd love this, too! 
We're facing a similar issue over here. 
I mean in theory the type of the main stream is there and for a ton of videos it really adds a huge overhead to transcode each of them if the TV doesn't support a certain codec but only some of the videos use that codec.

So some sort of advanced filter would be pretty useful considering most compatibility issues are caused by an unsupported codec, not by the video container format for 90% of the time.

**Comment by kyak** [comment]
@KarlStraussberger I don't think this issue can be closed by that commit unless I misunderstood something.

I've tried using `client-flags` transcoding profiles and they work just fine. However this issue is about ability to differentiate between codecs used in a specific container (or mimetype).

Thus, "Allow codec specific transcoding" would be super-awesome!

**Comment by KarlStraussberger** [comment]
So it's "Alow client and codec specific transcoding" because on other clients you want other codec 😸

**Comment by Hospes** [comment]
> So it's "Alow client and codec specific transcoding" because on other clients you want other codec 😸
@KarlStraussberger not really, as I understood this allow us to specify for which client we want to transcode video, is it right ?
From config and commit ocmments I understood that this gonna help to differentiate specific (old) model of samsung from LG (for example) so for example if it's old samsung then we do transcoding, but this not solve the main issue. How to transcode files that are encoded with HVEC and not transcode file for other codecs.
The only solution that comes to my head is based on file names for example. If file has suffix or contains strings like "hvec" or "h265" then transcode it.

**Comment by kyak** [comment]
> > So it's "Alow client and codec specific transcoding" because on other clients you want other codec 😸
> 
> @KarlStraussberger not really, as I understood this allow us to specify for which client we want to transcode video, is it right ?
> From config and commit comments I understood that this gonna help to differentiate specific (old) model of samsung from LG so for example if it's old samsung then we do transcoding, but this not solve the main issue. How to transcode files that are encoded with HVEC and do not transcode for other codecs.
> The only solution that comes to my head is based on file names for example. If file has suffix or contains strings like "hvec" or "h265" then transcode it.

It seems to me that Karl has recognized it, hence #1738 

Thanks @KarlStraussberger !
