### ISSUE TITLE
TagLibHandler messages are very misleading

### ISSUE THREAD

**Issue by whorfin** [gerbera/gerbera#1271]
This bit of code in src/metadata/taglib_handler.cc line 415 in v1.7.1 is indicative of the issue:
```
    if (!mp3.isValid() || !mp3.hasID3v2Tag()) {
        log_info("TagLibHandler {}: could not open mp3 file",
            item->getLocation().c_str());
        return;
    }
```
Old mp3s which are valid but not containing modern tags will clog the logs with an incorrect message that they could not be opened, which sounds like a permission or other file access problem.  It would be much friendlier, if "info" messages are to be given, to produce proper info - "Invalid mp3 file" and "contains no ID3v2Tag" for example

This same misleading idiom can be found for most file types

**Comment by KarlStraussberger** [comment]
The message is rather old. Maybe it's the first time you ran across it.

It used to be a debug message in 1.6.0, but looking at the return right after it, it's worth beeing on info level, because no tags are imported from that file.

There's some need to investigate taglib docs for additional details to print in the message.

**Comment by whorfin** [comment]
You are right, it's not a new message, it's been so long since i've rebuilt my database i guess i forgot
The new behavior and database migration is somehow causing it to get revisited, so this time i really paid attention to what was going on, and discovered it to be wrong (ie the file _is_ accessible, it's just the message saying something other than the truth)

**Comment by KarlStraussberger** [comment]
> reading your comment more carefully, if it were introduced in 1.6.0, i would not have seen it, as database import either went smoothly without that message, or i had other problems and deleted the log and never saw it

You never saw it because you normally do not run gerbera with `--debug`. Considering your number of media files, you propably never missed the skipped files.

**Comment by KarlStraussberger** [comment]
> The new behavior and database migration is somehow causing it to get revisited, so this time i really paid attention to what was going on, and discovered it to be wrong (ie the file _is_ accessible, it's just the message saying something other than the truth)

Need to look into taglib to get the message right or split into two.

**Comment by whyman** [comment]
The logic there is not ideal actually

` if (!mp3.isValid() || !mp3.hasID3v2Tag()) {`

We should try to extract the generic tags even without a `ID3v2` tag(s) (because it likely will have `ID3v1` tags)

But then should check the for v2 tags before trying to check for artwork (which is not supported by `ID3v1`)
