### ISSUE TITLE
m3u playlists broken, do not update after successful import

### ISSUE THREAD

**Issue by ckris1** [gerbera/gerbera#1670]
I've updated from 1.7 to 1.8.2 on Fedora 34 just recently:
Version     : 1.8.2
Release     : 1.fc34
Architecture: x86_64

I recreate a couple of m3u playlists every night. They're randomized so my media players can offer a new mix of music every day.
The folder which holds these m3u files is monitored using INotify.

Gerbera notices the file change and according to the log the new m3u are succesfully imported. However, the contents of the playlists presented to any UPNP client is not updated. They always "see" the same outdated playlist.

With the previously used 1.7 this was working without issues.

**Comment by KarlStraussberger** [comment]
To improve performance updates (signals and ids representing changes) are only created if a container was changed. In your case the container containing the playlist items is not changed and no update is sent to the clients.

To work around this, you may just delete the m3u file and create it again instead of just updating its contents.

**Comment by ckris1** [comment]
okay, but a "touch *m3u" seems to be sufficient.

**Comment by KarlStraussberger** [comment]
Anyway, I am thinking about to update the playlist script and other code to handle the change properly.

**Comment by KarlStraussberger** [comment]
I added two more Samsung extensions to UPnP actions. Can you try these out and grab the new debug-log.
Thank you.
