### ISSUE TITLE
Smart Pointers vs. Traditional Pointer

### ISSUE THREAD

**Issue by elmodaddyb** [gerbera/gerbera#225]
Hello,

I am working to make Gerbera more unit test friendly.  Gerbera has an implementation of smart-pointer via `zmm::Ref` which allows most code to care nothing about pointer cleanup, etc.  This makes for easy implementation, but forces requirement of `zmm::Object` and its hierarchy.

I am wondering if anyone has an opinion on these **smart pointers**.

```c++
// Should we use and manage pointer allocations traditionally.
MyClass* anInstance = new MyClass();
```
OR
```c++
// Should we use smart pointers consistently?
zmm::Ref<MyClass> anInstance(new MyClass())
```

All thoughts, feedback, experience welcome.  My c++ experience is novice so any insight is appreciated.

Thanks,
Eamonn

**Comment by gburca** [comment]
Managing pointer allocations manually is typically error-prone and not a good idea unless there are no other choices (consider freeing memory when exceptions are thrown, etc...). On the other hand, zmm::Ref has probably out-lived its usefulness. C++ has had a full complement of standard smart pointers (`unique_ptr`, `shared_ptr`, `weak_ptr`) since c++11 which don't impose any inheritance requirements. I would recommend switching to those wherever and whenever practical.

**Comment by v00d00** [comment]
@gburca is absolutely correct, so closing this :+1: 

If its new code, try to avoid `zmm::Ref` where possible.

Once we get around to replacing the arrays classes with normal STL variants then we can switch to `shared_ptr` across the board.

**Comment by elmodaddyb** [comment]
@gburca @v00d00 - Thanks for the feedback.  I was thinking `zmm:Ref` was relic from another time before `unique_ptr` etc were available...  Thanks for the recommendation!
🥇
