### ISSUE TITLE
MariaDB 10.1: Browsing broken

### ISSUE THREAD

**Issue by cweiske** [gerbera/gerbera#238]
When using MariaDB 10.1 ([Default on Debian 9](https://mariadb.com/resources/blog/mariadb-server-default-debian-9)) as database, I cannot browse my library anymore with clients:

They get a HTTP error 501, "action failed".

The log says why:
```
INFO: Exception: Mysql: mysql_real_query() failed:
mysql_error (1235): "This version of MariaDB doesn't yet support 'LIMIT & IN/ALL/ANY/SOME subquery'";
query: SELECT `id` FROM `mt_cds_object` WHERE ( `dc_title`LIKE 'cover.jp%' OR `dc_title`LIKE 'albumart%.jp%' OR `dc_title`LIKE 'album.jp%' OR `dc_title`LIKE 'front.jp%' OR `dc_title`LIKE 'folder.jp%' ) AND `upnp_class`='object.item.imageItem' AND ( ( `parent_id` IN (SELECT `parent_id` FROM `mt_cds_object` WHERE `upnp_class`='object.item.audioItem.musicTrack' AND `id` IN (SELECT `ref_id` FROM `mt_cds_object` WHERE `parent_id`='564' AND `object_type`=2 LIMIT 100))     ) OR `parent_id`='564') LIMIT 1
```

This `LIMIT 100` was introduced in 6dfe3ee7b513116cf6a01f0e2e3620a121b82ac4 by @whorfin.
Reverting that commit makes it work again on MariaDB.

Also see https://mariadb.com/kb/en/library/subquery-limitations/

> MariaDB doesn't support LIMIT in subqueries with certain subquery operators.

**Comment by whorfin** [comment]
I'd be tempted to say that means MariaDB isn't compatible with gerbera, then.
That LIMIT is important for performance with large collections, at least with current optimizers for sqlite

If it is helpful, I'd be happy to add a #define switch allowing that to be disabled, though rely on someone else to hook it up to detect MariaDB.
Is it only the subquery LIMIT which is unsupported?

**Comment by whorfin** [comment]
[maybe a simpler way would be to simply allow setting MAX_ART_CONTAINERS to 0, and disable the LIMIT in that case]

**Comment by astylos** [comment]
If MariaDB is now the default in Debian, rather than mysql, then more users are going to hit this issue. I think it would make sense for gerbera to handle this situation nicely. If it can't be handled at runtime, then at least at build time so gerbera documentation points this out to anybody building from source (including those packaging for Debian).

**Comment by whorfin** [comment]
I leave it to those who know the Debian 9 configuration to perform the shenanigans, but the makin's are here now when this pull is done.

**Comment by jcowgill** [comment]
FYI, I also get this error with MySQL 5.7, so it's not just MariaDB which this is broken on.

**Comment by cweiske** [comment]
@whorfin if it does not work on MySQL 5.7, where does that subselect limit  work then?

**Comment by whorfin** [comment]
SQLite

**Comment by whorfin** [comment]
Since this was intended to help MySQL as well, and since it appears MySQL _still_ doesn't support subselect limits, I'll re-work this to require enabling, rather than defaulting to on.

**Comment by lyallp** [comment]
It should be noted if there is lots of media, in my case I had gerbera index my photos and music/podcast collection, clients would time out (in particular, my LG TV), when I told gerbera to not index my music/pictures, browsing my videos become much snappier with no timeouts.

**Comment by whorfin** [comment]
@lyallp - if the performance hit of this fallback hits you too hard, you might try adding a
-DONLY_REAL_FOLDER_ART=1
when you do your first cmake, and see if that helps.  It skips album art for virtual listings.

I found that regardless of optimization [ie I could totally disable album art] I have seen truly horrible performance on indexed/virtual directories ["Audio/Albums" rather than "PC Directory"] on some DLNA
clients, such as mobile foobar2000.  It would be interesting to see if other servers have this same problem [minidlna?] or if there's something unique in the gerbera architecture that makes this worse.

**Comment by lyallp** [comment]
There are some horrible sql queries that cause the problem when you have tens of thousands of media objects. I spent time looking at the queries being processed by my mariadb server on my home PC under Linux, some queries where over 5 seconds execution time. Rather than tuning the queries, I figured I had never looked at the music/photos/podcasts via gerbera so I disabled indexing them, problem solved, for me. So, my mt_cds_object table contains less than 33k rows and performs well, whereas before, it contained over 300k rows and my TV got bored waiting and timed out.

**Comment by cweiske** [comment]
The original problem mentioned here (does not work with mariadb 10.1) is fixed since a long time.
Today I updated to 1.9.1, and it works fine with mariadb 10.3.

Browsing performance in 1.9 is much better than in earlier versions.

Closing this.
