### ISSUE TITLE
Crash with js layout when track number is -1

### ISSUE THREAD

**Issue by jerome-pouiller** [gerbera/gerbera#2398]
If I use  `<virtual-layout type="js">` and the track number of one my music is `-1`, I get this error:
```
terminate called after throwing an instance of 'std::out_of_range'
  what():  stoi
```

I have seen this issue on 1.9.2 and on master, but I think it didn't exist on revision 1.7.0.

If I comment all calls to `addCdsObject()`, the problem disappears.

I tried to trick `obj.meta[M_TRACKNUMBER]`, but it seems it is not sufficient.

**Comment by KarlStraussberger** [comment]
Thanks for your report. 

This really interesting. Without reading the specs, but from taglib implementation and Windows Explorer behaviour, negative number should not be allowed here. Taglib returns it as unsigned int which is stored as int in the database und in javascript. Thus we create a nice overflow error.

In order to be consistent, the fix must be to block negative numbers (i.e. cut at max-int).
