### ISSUE TITLE
Missing Album Artist results in no artist

### ISSUE THREAD

**Issue by neheb** [gerbera/gerbera#2648]
Starting with Gerbera 1.10, it seems [Copy artist to album artist for container  ](https://github.com/gerbera/gerbera/commit/24bc9e38f426e7874b5a681aea0c508032b34bfc) was reverted.

**Comment by KarlStraussberger** [comment]
This piece of code is not needed anymore because it is an old entry point for javascript `addContainerChain`. The new interface `addContainerTree` and corresponding scripts set Album artist directly https://github.com/gerbera/gerbera/blob/1b6ffa66367d49677074899fe3de383d5ba03813/scripts/js/common.js#L360-L375

What's the issue?

**Comment by KarlStraussberger** [comment]
Issue seems you've got an import script issue with an old javascript file (#2649).

**Comment by neheb** [comment]
Seems like it.

**Comment by KarlStraussberger** [comment]
It's still the question of import which was changed before 1.9.2

**Comment by neheb** [comment]
Bisected. https://github.com/gerbera/gerbera/commit/379f76f68ac027c052fe77dd502f74a2553b53bf breaks this.

**Comment by whyman** [comment]
Maybe we should remove the built-in layouts?

Now we use duktape it's no longer a giant dependency like libmozjs was

**Comment by KarlStraussberger** [comment]
We can keep it with it's reduced features but no effort to make it work like the js-layout: It works well if all data is as expected and it works if folks want a locked system.
