### ISSUE TITLE
Support Radio-Browser internet-radio database

### ISSUE THREAD

**Issue by renne** [gerbera/gerbera#2768]
Most internet-radio devices use some kind of database in the internet for radio programs/channels.
Sooner or later the vendor ends support for that database and the internet-radios cannot receive internet-radio streams anymore. Although the hardware is fine, the devices end up as electronic waste.

Most of these internet-radios work as UPNP/DLNA Media Renderers.
[Radio-Browser](https://www.radio-browser.info/) is an open-source community-driven internet-radio database with 36,000 programs/streams .
Even if the maintainer steps down it can be taken over by other volunteers.

So I suggest to implement the [Radio-Browser database](https://www.radio-browser.info/faq) in Gerbera to make these internet-radios usable again via UPNP/DLNA.
With the transcoding feature in Gerbera even very old internet-radios can have a second life.
This will save a lot of electronic waste!

The [Radio-Browser API documentation](https://api.radio-browser.info/)) lists library implementations for multiple programming languages.

**Comment by KarlStraussberger** [comment]
That sound like a great idea and a lot of work. If you know what to do, you may implement it as OnlineService.

For a starter you can already add external urls to your favourite stations.

**Comment by trex2000** [comment]
I actually use for this purpuse Gerbera. I have some old Sony interenet radios that used to work via some service provided by Sony, which are no longer available.
These do support DLNA and mpeg/lpcm16 codecs, therefore I added the URLs of ther radio stations and I am using ffmpeg (or avconv) to re-encode on the fly the stream and restream it to the Internet radio.
I am having trouble since i've switched to newer gerbera , but with older version this was working fine for years.
Basically, make sure you have:
`        <treat mimetype="audio/mpeg" as="mp3" />`
under       <mimetype-contenttype>
Then,
Set   <transcoding enabled="yes"> and define the 
  `  <mimetype-profile-mappings>`
to be able to transcode the audio/mpeg mimetypes:
      <transcode mimetype="audio/mpeg" using="streaming-transcode"/>

Then under <profiles>
you can  add the transocding profile:
```
      <profile name="streaming-transcode" enabled="yes" type="external">
       <mimetype>audio/mpeg</mimetype>
         <first-resource>yes</first-resource>
           <accept-url>yes</accept-url>
           <sample-frequency>48000</sample-frequency>
           <audio-channels>2</audio-channels>
           <hide-original-resource>yes</hide-original-resource>
           <agent command="avconv" arguments="-i %in  -rtbufsize 1M -acodec mp3 -ab 128k  -bufsize 1M  -ar 48000 -ac 2 -async 1 -f mp3 -y %out"/> 
           <!-- <buffer size="1024000" chunk-size="51200" fill-size="25600"/> -->
           <buffer size="4096000" chunk-size="131072" fill-size="262144"/>
     </profile>
```
Add the radio stations :
Title, what you wish,  Location is the URL which you can extract by inspecting a webpage that plays the stream, and  specify as mime-type audio/mpeg

Also adjust in the profile the <agent command> to your needs (if you don't have on your system avconv , you have for sure ffmpeg or vlc

**Comment by trex2000** [comment]
![Clipboard01](https://github.com/user-attachments/assets/e425eb32-891a-4f32-8b6b-6dcf947fa59b)

**Comment by trex2000** [comment]
[config.xml.txt](https://github.com/user-attachments/files/17258735/config.xml.txt)
