### ISSUE TITLE
Gerbera 1.12 not showing up on the network

### ISSUE THREAD

**Issue by Tyg-g** [gerbera/gerbera#2891]
Hi Guys, I don't really have any ideas how to troubleshoot or find out what is the problem. I updated  to Kubuntu 23.10 - it comes with gerbera 1.12 (instead of 1.1 in the previous distro versions).

The previous versions worked normally. But the 1.12 does not show up on the TV, nor in the `gupnp-universal-cp` tool.

If I run the previous version (1.1) in VirtualBox, it shows up normally on all other devices on the network.

Please help me with troubleshooting

**Comment by udippel** [comment]
Stupid question: Does the web interface show; on the local machine and on another machine?
Are you sure you can ping the server?
What is the output of `nmap <server-IP>`?
What is the output of `ps ax | grep gerbera`?

**Comment by Tyg-g** [comment]
1. Not stupid at all. The web interface is working without a problem, it shows up everywhere. Only the UPnP part has the problem.
2. I can ping my computer (the one running gerbera) from my phone and from the VirtualBox. Otherwise I'm not sure how to ping an UPnP server.
3. 
```
tyg@Tyg-ThinkPad:~$ nmap 192.168.1.20
Starting Nmap 7.94SVN ( https://nmap.org ) at 2023-10-29 16:38 CET
Nmap scan report for Tyg-ThinkPad (192.168.1.20)
Host is up (0.00014s latency).
Not shown: 998 closed tcp ports (conn-refused)
PORT      STATE SERVICE
6881/tcp  open  bittorrent-tracker
49152/tcp open  unknown

Nmap done: 1 IP address (1 host up) scanned in 0.07 seconds

```
4.
```
tyg@Tyg-ThinkPad:~$ ps ax | grep gerbera
  12066 ?        SLsl   0:00 /usr/bin/gerbera -c /etc/gerbera/config.xml
  12105 pts/2    S+     0:00 grep --color=auto gerbera
```

So these are the answers for your questions. Thanks for taking time for this issue.

**Comment by udippel** [comment]
Sorry, but I'm just an old *nix guy, though most fresh on gerbera myself. 
What I find strange is the 0:00 of time used by gerbera. It looks like it had never done anything.
While daemonizing services is a good idea, for troubleshooting it is just a hoop to go through. In case you like to go further until the master is back, I'd personally un-daemonize it:
`$ sudo systemctl stop gerbera` (check with `ps ax | grep gerbera` that it is really gone.)
Run it manually from the command line instead. And using its own, self-generated config file to see what its log tells us by starting from scratch. This shouldn't affect the daemonized installation. I'd just 
`$ gerbera -d -l testrun.log` 
and then play briefly with it, adding some test media files through the web interface. Followed by
`$ ps ax | grep gerbera`
and then 
`$ kill <process number popping up; in your example it would have been 12066>`
Followed by looking at the content of `testrun.log`, respectively showing it here. 

No promises, but I have myself experienced a bad history of gerbera updates. So starting a virgin session from the command line might get us a step further.?

**Comment by Tyg-g** [comment]
I did as you suggested. I clicked around in the web interface. I deleted some files, tried adding some files. Adding individual files (with the + icon) doesn't work, adding whole directories does. 

I had 2 UPnP clients (TV + tool) running to generate UPnP traffic. Of course they didn't recognize gerbera. Here is the log file contents. Looks like gerbera has no problems with itself.

```
2023-10-30 10:21:42   info: Gerbera UPnP Server 1.12.1 - http://gerbera.io/
2023-10-30 10:21:42   info: Copyright 2016-2022 Gerbera Contributors.
2023-10-30 10:21:42   info: Gerbera is free software, covered by the GNU General Public License version 2
2023-10-30 10:21:42   info: Daemonized.
2023-10-30 10:21:42   info: Loading configuration from: /home/tyg/.config/gerbera/config.xml
2023-10-30 10:21:42   info: Checking configuration...
2023-10-30 10:21:42   info: Configuration check succeeded.
2023-10-30 10:21:42   info: Loading 3 configuration items from database
2023-10-30 10:21:42   info: Loading autoscan location: /media/Dolgok/Downloads/Films; recursive: true, mt: 81/Audio | Image | Video, last_modified: 2023-10-30 07:14:43
2023-10-30 10:21:42   info: Initialising UPnP with interface: <unset>, port: <unset>
2023-10-30 10:21:43   info: IPv4: Server bound to: 192.168.1.20:49152
2023-10-30 10:21:43   info: IPv6: Server bound to: fe80::2905:bca8:7d47:62e2:49152
2023-10-30 10:21:43   info: IPv6 ULA/GLA: Server bound to: :0
2023-10-30 10:21:43   info: Will send UPnP Alive advertisements every 60 seconds
2023-10-30 10:21:43   info: The Web UI can be reached by following this link: http://192.168.1.20:49152
2023-10-30 10:26:04   info: Gerbera shutting down. Please wait...
2023-10-30 10:26:04   info: Gerbera exiting. Have a nice day.
```

The 0:00 could be explained by that gerbera didn't run long enough to collect 1s of processor time.

I guess this issue is specifically related to UPnP or the UPnP libraries. I also tried to install gerbera 1.12 on an older Ubuntu installation in VirtualBox and that does show up in the UPnP clients. I'm stuck.

**Comment by udippel** [comment]
Thanks for trying!
Okay, this testrun.log doesn't show a virgin session, since it loads items from a database. One that, as far as I had thought, would not exist at that location:
`2023-10-30 10:21:42   info: Loading 3 configuration items from database
`
If it started from scratch, it would rather look like 
```
2023-10-30 14:16:08   info: Configuration check succeeded.
2023-10-30 14:16:08 warning: Sqlite3 database seems to be corrupt or doesn't exist yet.
2023-10-30 14:16:08   info: No sqlite3 backup is available or backup is corrupt. Automatically creating new database file...
2023-10-30 14:16:08   info: database created successfully.
```
In my (short) time on gerbera, the database.db had always been created automatically in the gerbera user's HOME. Not in .config/gerbera; using the autogenerated config.xml (THAT one always was in .config/gerbera, however).

_I also tried to install gerbera 1.12 on an older Ubuntu installation in VirtualBox and that does show up in the UPnP clients._
I'm not actually stuck with this. Many people, including myself, found gerbera 1.12 working principally okay. 

Since your effort did not start a virgin session, from scratch, no config.xml, no database, we can still not exclude the existing file to interfere. I see a 50% chance that a really new and fresh session will actually work. 
The other 50% then would point to a problem with kubuntu 23.10. 

The serious debugging exercise would therefore consist of moving the existing gerbera settings and database from before the upgrade totally out of the way to start that virgin session. 
And, secondly, making a basic new install of kubuntu 23.10, and just install gerbera. Should the latter not work, I'd file a bug with kubuntu. 
I won't take bets, but I expect BOTH to work.

**Comment by jerome-pouiller** [comment]
FYI I encountered the same issue. I solved it by setting a explicit `udn` in `config.xml`
