### ISSUE TITLE
Next Release Number for Gerbera 1.13, 1.24 or 2.0

### ISSUE THREAD

**Issue by KarlStraussberger** [gerbera/gerbera#2943]
After all the changes in the past year, the new release is not far away. What should its number be?

**Comment by cweiske** [comment]
Given the backwards-compatibility breaking changes in the import scripts, it should not be 1.x anymore. I vote for 2.0

**Comment by udippel** [comment]
Likewise here. Having seen only a few of the changes, they are considerable. 

Should the new default import method be grb?

I like(d) the concise help at start, and --check-config. Recently I find it cluttered, since I've seen 
`info: Created default BoxLayout key=Audio/artistChronology, title=Album Chronology, objClass=object.container, enabled=true, size=1
`with each start, with each --check-config. To me, this begins to look silly. And the line is the only one sooo long that it needs to wrap.
We've learned it is required, so by all means, if it isn't there yet, add and note it the first time, and then remain silent.

I don't think we have it yet, or can achieve this until the next release, that - similar to database update - we can merge newly introduced and relevant items into an existing config; or at least show a diff-like list? 
Would in my case (though that's irrelevant, only as example) have found that this key is missing; instead of dying. 
Creating a newly defined default config.xml and manually merge existing settings isn't necessarily easy. And especially the default config.xml has changed very much since the last release.
