### ISSUE TITLE
gerbera 2.0 - ignore extensions?

### ISSUE THREAD

**Issue by nobanzai** [gerbera/gerbera#2969]
i want to exclude some file extensions from scanning, because they cause lots of mime errors in the log.
This
```
    <mappings>
      <ignore-extensions>
        <add-file name="bup"/>
...
      </ignore-extensions>
    </mappings>
```
seems to be the wrong way, but what else can I do?

**Comment by KarlStraussberger** [comment]
From my point of view the config works, but it's the cause of the log messages.

**Comment by FlashSystems** [comment]
I'd like to chime in on this bug as well. I'm using `<extension-mimetype ignore-unknown="yes">` and every unknown file extension results in these two log messages:

* `error: Mime not found for file` 
* `error: Object not created for file`

I think logging them as errors is too much. In my opinion, these aren't errors at all because everything is working as configured. Maybe these messages could be toned down to loglevel INFO?

**Comment by nobanzai** [comment]
> From my point of view the config works, but it's the cause of the log messages.

So it logs errors for files, that are not taken note of in further processing?

**Comment by KarlStraussberger** [comment]
I think, it used to be a valid error. But, we added more logic which should suppress the message - on it's way.
