### ISSUE TITLE
The system encountered an error

### ISSUE THREAD

**Issue by SergeyAka** [gerbera/gerbera#301]
Hi!
I've just installed Gerbera 1.2.0. It starts normally, but when I try to log in or navigate to any user's menu  button there is an error message occurs: **The system encountered an error**
Screenshot: https://yadi.sk/i/EnawzHWz3VmrBu

After error message was shown there in terminal occurs another message: Error of segmentation... And gerbera is closed.

Manjaro, Linux 4.16.7-1
Installed both libupnp 1.6.25 and 1.8.3-4

P.S.
After installation of gerbera is completed there are some warnings in terminal:
error: file owned by 'libupnp' and 'pupnp': 'usr/include/upnp/UpnpGlobal.h'
error: file owned by 'libupnp' and 'pupnp': 'usr/include/upnp/UpnpInet.h'
error: file owned by 'libupnp' and 'pupnp': 'usr/include/upnp/UpnpIntTypes.h'
error: file owned by 'libupnp' and 'pupnp': 'usr/include/upnp/UpnpStdInt.h'
error: file owned by 'libupnp' and 'pupnp': 'usr/include/upnp/UpnpString.h'
error: file owned by 'libupnp' and 'pupnp': 'usr/include/upnp/UpnpUniStd.h'
error: file owned by 'libupnp' and 'pupnp': 'usr/include/upnp/ithread.h'
error: file owned by 'libupnp' and 'pupnp': 'usr/include/upnp/ixml.h'
error: file owned by 'libupnp' and 'pupnp': 'usr/include/upnp/ixmldebug.h'
error: file owned by 'libupnp' and 'pupnp': 'usr/include/upnp/upnp.h'
error: file owned by 'libupnp' and 'pupnp': 'usr/include/upnp/upnpconfig.h'
error: file owned by 'libupnp' and 'pupnp': 'usr/include/upnp/upnpdebug.h'
error: file owned by 'libupnp' and 'pupnp': 'usr/include/upnp/upnptools.h'
error: file owned by 'libupnp' and 'pupnp': 'usr/lib/libixml.so'
error: file owned by 'libupnp' and 'pupnp': 'usr/lib/libupnp.so'
error: file owned by 'libupnp' and 'pupnp': 'usr/lib/pkgconfig/libupnp.pc'

**Comment by elmodaddyb** [comment]
@SergeyAka - based on the error message provided it sounds like you have 2 installations of the upnp in similar paths.

I wonder what the contents of this file are... `usr/lib/pkgconfig/libupnp.pc`

You might have to cleanup and remove the `libupnp 1.6.25` or install `1.8.3` to `/usr/local` to differentiate which library is used by gerbera.

**Comment by elmodaddyb** [comment]
@SergeyAka - Sorry for the delay as I was away for a bit.

Let me see if I can craft a Dockerfile for Archlinux to identify the installation sequence....will reply with `Dockerfile` if I have any luck.

**Comment by elmodaddyb** [comment]
@SergeyAka - I made some progress by creating a Archlinux Dockerfile.

### Success Scenario
I created a **dockerfile** which uses the _Archlinux_ base as the starting point.

[Dockerfile.arch - working](https://github.com/elmodaddyb/gerbera-docker/commit/2e8b27a4a2b7ae2e4b089aadff8c81d1712e2b25#diff-2a061f4f8c17bfb669fa4a164575976d)

The dockerfile installs `libupnp` using the provided script from `gerbera/scripts/install-pupnp18.sh` and everything compiled OK.

### Failing Scenario

I replaced the `install-pupnp18.sh` with the `AUR` version at

[Dockerfile.arch - broken](https://github.com/elmodaddyb/gerbera-docker/commit/fd00e921327eaf6a013bc62d5fed90ee6a880e11#diff-2a061f4f8c17bfb669fa4a164575976d)

This is where I now get the error similar to your mention:

```cmake
-- Could NOT find UPnP (missing: UPNP_UPNP_LIBRARY UPNP_INCLUDE_DIR) 
CMake Error at CMakeLists.txt:349 (message):
  gerbera requires libupnp 1.8.3 or above.
```

### Possible Root Cause

When I review the installation log for the AUR package, it installs the package directly into the **git cloned** working copy.

```
make[1]: Entering directory '/build/libupnp18/src/libupnp-1.8.3'
make[2]: Entering directory '/build/libupnp18/src/libupnp-1.8.3'
 /usr/sbin/mkdir -p '/build/libupnp18/pkg/libupnp18/usr/lib/libupnp-1.8/pkgconfig'
 /usr/bin/install -c -m 644 libupnp.pc '/build/libupnp18/pkg/libupnp18/usr/lib/libupnp-1.8/pkgconfig'
make[2]: Nothing to be done for 'install-data-am'.
```
I am not too familar with Archlinux yet, but maybe there is a way to install this globally into `/usr/local` by overriding a setting during the `makepkg` command?

> Since the provided script installs and works, I wonder if there is some missing configuration in the **makepkg** of the AUR package??

**Comment by elmodaddyb** [comment]
I made progress with the AUR installation.  Everything for `libupnp1.8` appears to be installing properly into `/usr/lib` but for some reason the Gerbera `FindLibUpnp.cmake` is not finding the library & includes.

> Still working on troubleshooting the CMAKE issue

**Comment by fedi1973** [comment]
I have the same issue with version 1.3.0alpha. When started with -D the last output line is:
2018-05-20 22:06:25   DEBUG: [src/singleton.cc:69] registerSingleton(): registering new singleton... - 6 -> 7
Speicherzugriffsfehler

Speicherzugriffsfehler means segmentation fault

**Comment by elmodaddyb** [comment]
**UPDATE**
I was able to successfully run a Archlinux VM and stream video to VLC on tvOS(Samsung) & VLC on iOS (mobile).  The movie played well with no issues.

I think 2 fixes are needed to clarify the build.

1. Update `FindLibUpnp.cmake` to exclude `libupnp` module check
2. Update `install-duktape.sh` to add `/usr/local/lib` to `/etc/ld.so.conf.d/local.conf`

However, I was unable to reproduce a **SIGSEGV** in any attempt....so not sure how much help these steps will be...
