### ISSUE TITLE
Non-existing file does not get removed from database

### ISSUE THREAD

**Issue by cweiske** [gerbera/gerbera#3138]
**Describe the bug**
I renamed some music files that have been indexed by gerbera already, and now on every restart two error messages are shown for one missing file:
```
error: Exception: [/usr/local/src/gerbera/gerbera-git/src/file_request_handler.cc:84] virtual const ClientInfo* FileRequestHandler::getInfo(const char*, UpnpFileInfo*) Error: Requested resource 1 does not exist
error: Exception: [/usr/local/src/gerbera/gerbera-git/src/file_request_handler.cc:108] virtual const ClientInfo* FileRequestHandler::getInfo(const char*, UpnpFileInfo*) Error: Failed to open /data/media/Music/Alben/Fool's Garden/Once in a Blue Moon/Fool’s Garden - Once in a Blue Moon - 14 - Once in a Blue Moon.ogg: No such file or directory
```

(I changed the `’` to a `'` in the meta tags and renamed the files)

**Expected behavior**
Missing files get deleted

**Server (please complete the following information):**
 - OS: Debian 12
 - Gerbera Version: v2.1.0-84-g65dd0859
 - Source: self built

**Media client (please complete the following / remove not applicable:**
Webbrowser

**Additional info**
May be related to #3135 (and #3091)

**Comment by cweiske** [comment]
I just see that *all* files in that folder did not get removed/updated. The one file logged comes from when the cover image is loaded for the artist/album.

**Comment by KarlStraussberger** [comment]
> Btw, how can I completely empty and rescan the database now?

In a brief: Remove PC Directory Contents

**Comment by udippel** [comment]
Yep. I had asked the same thing a number of times earlier, and was given the same answer few weeks (if at all) ago. 

Let me repeat my suggestion, to add a feature button for 'just recreating the database from scratch'. I don't think that would hurt.

**Comment by KarlStraussberger** [comment]
> I just see that *all* files in that folder did not get removed/updated. The one file logged comes from when the cover image is loaded for the artist/album.
> 
> The files were renamed before I updated to the #3135 source code version.
> 

Files are only rescanned if the timestamp changes, so Gerbera can be cheated by resetting modification time.

**Comment by KarlStraussberger** [comment]
Cannot reproduce any issue here.

**Comment by KarlStraussberger** [comment]
@cweiske can you check that with you modified import scripts, please.

**Comment by udippel** [comment]
When is it supposed to be noticed by gerbera? 
Only a few weeks ago I added to my `ro` device, that was perfectly well updated at restarts of gerbera, an `rw` device. 
It had shown a behaviour similar to what @cweiske had noticed (files remain visible in the database view) since.

Now, with 2.2.0-12, restarted an hour ago, I removed a file through a system call; not through the web interface.
I checked immediately with`ls`. It was gone. Some 15 minutes later it still shows in the database view of the web interface. A browser reload didn't bring any change. Since the URL doesn't show any sub dir that could be reloaded explicitly, I logged out and in again. The file still shows in the database. In the files view it is gone, naturally. 
Clicking it results in a 404.

import mode is `grb`, `mode="inotify" recursive="yes"` for the rw drive.

**Comment by udippel** [comment]
Had some time to explore this (debug files run up to some 100 MB).
Started gerbera in debug mode, waited for it to settle. 
Deleted one specific file.
Waited for it to settle.
This is the debug log from the first occurrence of the filename of the file deleted (searched vi) to the end (time) of that singular occurrence.
[No_delete.log](https://github.com/user-attachments/files/16389726/No_delete.log)

**Comment by udippel** [comment]
Deleted my previous comment, since I had an idea from that other thread #3167.

> A browser reload didn't bring any change. Since the URL doesn't show any sub dir that could be reloaded explicitly, I logged out and in again. The file still shows in the database.

Did the same that was suggested over there, a hard `Shift+Ctrl+R`. It logged me out, and after login, the file IS actually gone. 
I don't know enough about cache and cookie handling, though it looks like something ought to be done about that. If a 'normal' reload and even login-logout don't do the job, it doesn't look good. 
(I do think that the 'solved' time-out of the login that doesn't work properly here, could have the same root cause. Only as a remark here; could be discussed elsewhere.)

So far I have mostly used Chrome on *buntu.
Will try Firefox next.

**Comment by udippel** [comment]
With Firefox it ain't different, alas. Only a restart guarantees an up-to-date display.

**Comment by udippel** [comment]
Had some time to explore this further. Set up a new gerbera most recent install on a box that had never seen gerbera before. Created a `test_dir` containing eight audio files Jamaïque_1_8... to Jamaïque_8_8... . Started gerbera with default settings `--create-config`, added these files through `Add Autoscan` Item in the `File System` View. Shut down.

Set to `--debug`, viewed the `test_dir`, saw the eight files, deleted (`rm`) Jamaïque_5_8... . Waited some time, reloaded the browser view, still showing the file. Only a restart could finally remove that file from the `Database` view. 
[That the seven remaining files (only) show under Recently Added, but nothing under Recently Modified is completely minor, though IMHHO not quite right, since the deletion of that single file was done after the addition, actually even a restart later. Or does the `Added` and `Modified` work on time frames, summarily, not on events?]

I have included the complete `--debug` file, from start to end, of that second run, the one that saw the deletion. 
[debug.log](https://github.com/user-attachments/files/16616341/debug.log)

Maybe it can help to understand why deletion is not reflected in the view of the (reloaded) web interface?

**Comment by KarlStraussberger** [comment]
I am fully aware of the issue but was not able to take a close look where it happens.

**Comment by udippel** [comment]
I hadn't understood that you are aware of this.
Somehow I think, the solution could be obvious: run the same procedure that updates web data at adding a file. 
I have started that test install as above, and `cp`-ed an `.mp3` file into it. Immediately it showed at `Recently Added` and `Recently Modified`, as well as in that `Database` directory.

**Comment by cweiske** [comment]
What was the problem?

**Comment by KarlStraussberger** [comment]
Several:
- Renaming files was not handled in inotify code for grb-mode
- Renamed/Removed files do not return filesystem info
- Moving files was not correctly implemented in database code

Just broke deleting files now 😦

**Comment by udippel** [comment]
Chapeau!
Works splendidly well here. Feels like another system.
May I suggest to move to 2.3, since this is a major step w.r.t. user experience, so that all users can enjoy this?
