### ISSUE TITLE
[FR] DSD Support

### ISSUE THREAD

**Issue by parkmino** [gerbera/gerbera#324]
Could it be possible to support DSD file format?

**Comment by parkmino** [comment]
Yes, DSD capable DAC is needed which supports native DSD or DoP(DSD over PCM).
AFAIK, AssetUPnP, DSD patched MiniDLNA, MinimServer, Logitech Media Server, JRiver MC for Linux supports DSD at the moment.
Please refer to the following link for the DSD patch for MiniDLNA for your reference.
https://sourceforge.net/u/takeshich/minidlna/ci/AddSupport4DSD/tree/

**Comment by parkmino** [comment]
I found out an workaround to play DSD in upmpdcli.conf
checkcontentformat = 0
Now, dff files show up and they play!
However adding DSD file formats to Gerbera would be great though.

**Comment by dieneuser** [comment]
DSD is possible in database too. I have been using this since version 1.1 to play DSD files (*.dsf oder *.dff). Only integrated covert art is not supported.
In the config.xml file, only the following lines must be added:
In the mappings node:
```
        <map from="dsf" to="audio/x-dsd"/>
        <map from="dff" to="audio/x-dsd"/>
```
And in the mimetype-contenttype node:
`        <treat mimetype="audio/x-dsd" as="dsd"/>`

Thats all. So i can play native DSD with my Sony AVR (STR-DN1070).

**Comment by parkmino** [comment]
Thanks for your information, it works on my side as well.
Registering DSD file types to config.xml as default should close this issue then.

**Comment by elmodaddyb** [comment]
@parkmino - Great news on the success.  I am familiar with the configuration defaults, so will post the defaults for DSD types soon.
