### ISSUE TITLE
Config file not found : misleading exception message

### ISSUE THREAD

**Issue by lolo101** [gerbera/gerbera#329]
When a config file is not found, an exception is raised with a static message :
> The server configuration file could not be found in ~/.config/gerbera

This message is misleading when using options to configure the location of the configuration file, like `--cfgdir` for instance.

The message should be dynamic.
https://github.com/gerbera/gerbera/blob/master/src/config_manager.cc#L116

**Comment by elmodaddyb** [comment]
@lolo101 - Thanks for the suggestion.  I am familiar with the `config_manager` class you mentioned.  I will push a change which uses the `home` variable for the output...rather than `~/.config/gerbera` (_hard-coded_).  This should help clarify when the system overrides with `--cfgdir`

Thanks for the help in identifying the code block! :smiley:
