### ISSUE TITLE
Sony TV (model KDL 32EX525) can't see MKV files

### ISSUE THREAD

**Issue by gabriellluz** [gerbera/gerbera#368]
Hi

I have a Sony TV, model KDL 32EX525. It uses exactly the same profile as a PS3. No differences. The thing is: all my movies in MKV are not being displayed. Also, my MP4 files with SRT subtitles inside the same folder with the same filename are not being used too. What can I do to solve this?

**Comment by elmodaddyb** [comment]
### MKV Files
I found that some UPnP endpoints do not recognize the movie files due to the way the `config.xml` has the `<mimetype-contenttype><treat>` types defined.  I was able to fool a few endpoints into playing MP4 files by using a mix of the transcoding and `<treat>`

> I wonder how your `config.xml` is **treating** the MKV files?  maybe this type is not identifiable by the Sony  TV?


### Subtitles
I think the subtitle resource is defined in an extra header when the **samsung hack** is enabled via configuration, not sure if this truly works otherwise:

`/server/protocolInfo/attribute::samsung-hack`  =  `yes/no`

> For samsung header....
https://github.com/gerbera/gerbera/blob/master/src/file_request_handler.cc#L270

> For rendering out the subtitle resource
https://github.com/gerbera/gerbera/blob/master/src/cds_resource_manager.cc#L463

**Comment by gabriellluz** [comment]
My TV Model works exactly the same settings for PS3.

**Comment by gabriellluz** [comment]
Hm... but if my TV can't play MKV files, shouldn't gerbera transcode it?

**Comment by gabriellluz** [comment]
I'm not talking about direct play. I really want my MKV files to get converted into MP4 so I can watch them with Gerbera.

**Comment by Martii** [comment]
@gabriellluz 

> ... shouldn't gerbera transcode it?

Well neither of my distros do that currently but I haven't dug into the config files much at all. What's additionally interesting is my NAS is much, much, much older and it's UPNP DLNA server is recognized by my older Sony devices... but slower than a snail.

> I really want my MKV files to get converted into MP4 so I can watch them with Gerbera.

There might be some conversion tool that maintains all the metadata out there. `ffmpeg` is usually what I use for just changing the container format quickly with a video and audio codec copy. But usually it's in AVC which is roughly four times larger on the file size compared to HEVC... but of course HEVC doesn't work on most Sony devices at this time. Was looking at a newer BDR and it claims to have HEVC support.

Since my extremely expensive at the time TV is EOL'd it almost never receives a firmware upgrade so I'm out of luck. It's still chugging along with the same picture quality. It's been "babied" on UPS since I bought it and has its own share of issues with the core software it contains.

I moved over to a HTPC *(Home Theater PC)* just to avoid all the planned obsolescence in appliances. Computers are easier to upgrade when needed... some things with a learning curve.
