### ISSUE TITLE
External link (URL) Item broken resulting link

### ISSUE THREAD

**Issue by Ne94fets** [gerbera/gerbera#426]
Hi,

Gerbera is running on a gentoo-system. 

If you I add an External Link (URL) Item via the web interface the resulting link gets "content" + "URL".

I made a hotfix for my machine, but I don't think this is the best solution.

```C++
diff --git a/src/upnp_xml.cc b/src/upnp_xml.cc
index 6a5f650f..b170b82b 100644
--- a/src/upnp_xml.cc
+++ b/src/upnp_xml.cc
@@ -569,9 +569,9 @@ String UpnpXMLBuilder::getFirstResourcePath(Ref<CdsItem> item)
 {
     Ref<PathBase> urlBase = getPathBase(item);
     if (urlBase->addResID) {
-        return _(SERVER_VIRTUAL_DIR) + urlBase->pathBase + 0;
+        return urlBase->pathBase + 0;
     }
-    return _(SERVER_VIRTUAL_DIR) + urlBase->pathBase;
+    return urlBase->pathBase;
 }
 
 String UpnpXMLBuilder::getArtworkUrl(zmm::Ref<CdsItem> item) {
@@ -931,7 +931,9 @@ void UpnpXMLBuilder::addResources(Ref<CdsItem> item, Ref<Element> element)
             log_debug("extended protocolInfo: %s\n", protocolInfo.c_str());
         }
         // URL is path until now
-        url = virtualUrl + url;
+	if (!IS_CDS_ITEM_EXTERNAL_URL(item->getObjectType())) {
+            url = virtualUrl + url;
+        }
 
         if (!hide_original_resource || transcoded || (hide_original_resource && (original_resource != i)))
             element->appendElementChild(renderResource(url, res_attrs));

```
This fix works for all of my DLNA-Devices. But non-external items in the Web UI are now missing the "content" part.

**Comment by elmodaddyb** [comment]
Great insight.  I too hit this problem just recently, when running the integration test for the new Streaming Playlist feature.

If i find some time, I will try to write up a test to solve it.

**Comment by elmodaddyb** [comment]
I took a look at this and see that we have an identification issue.  It seems like you tracked this down accurately.  

What I think is happening is the following:

1. An `external-url` type saves the URL as the path
2. In most cases, this is a directory path, and needs to be appended properly to retrieve the resource
3. In the case of `external-url` the system should just return the *path* which is the URL

> The system should not try to determine the content location from the file system.  i.e. `SERVER_VIRTUAL_DIR`

We would need to ensure that the *external* identifier is available when rendering out the download URLs for the items.  More research is needed.

**Comment by elmodaddyb** [comment]
OK, I was able to find the root cause of this issue and fix.  It is due to the refactoring of the UPNP XML Builder implementation.

> External URLs previously worked, until revision https://github.com/gerbera/gerbera/commit/8660b5fa64c838c3b0b4d22377e518c73fd284cc#diff-520f4156117065a960e3087182acf4b4R194

After this, the `virtualDir` property is populated, and results in default URL paths to virtual content.
This works well for local content, but fails for External Content.

```xml
<res>http://localhost:49152/contenthttp://localhost:8080/stream</res>
```

The fix requires a few changes as mentioned previously.

1. Include a check for `IS_CDS_ITEM_EXTERNAL_URL` in [upnp_xml.cc - first resource](https://github.com/gerbera/gerbera/blob/master/src/upnp_xml.cc#L568)
2. Include a check for `IS_CDS_ITEM_EXTERNAL_URL` in [upnp_xml.cc - album artwork](https://github.com/gerbera/gerbera/blob/master/src/upnp_xml.cc#L577)
3. Include a check for `IS_CDS_ITEM_EXTERNAL_URL` in [upnp_xml.cc - addResources](https://github.com/gerbera/gerbera/blob/master/src/upnp_xml.cc#L934)

> I have an integration suite in the works that will validate this external URL behavior going forward...
