### ISSUE TITLE
avi not recognized

### ISSUE THREAD

**Issue by ringprince** [gerbera/gerbera#493]
I have just installed gerbera on a debian 9 (armel) system.  Works great in general for all mp4 files.  I have plenty of older avi or mpg files.  These do not show up in any client (vlc on linux or yaacc on android).

Is this a general problem or do I need some special configuration?

I've tried without success to enable

        <map from="avi" to="video/divx"/>

or

        <map from="avi" to="video/avi"/>

(and I have restarted gerbera afterwards).

**Comment by Martii** [comment]
> `<map from="avi" to="video/divx"/>`

> `<map from="avi" to="video/avi"/>`

Unless you know for sure that these are the MIME Content-Type for all of your media it may be better to not do this sort of mapping. According to [*mime-db*](https://github.com/jshttp/mime-db/search?q=avi&unscoped_q=avi) from official sources *(and Ubuntu (Intel/AMD 64 bit distro))* the MIME Content-Type is `video/x-msvideo`. 

For some sample test videos, if you wish, you can look at https://github.com/gerbera/gerbera/issues/471#issuecomment-496384668 for the  clock sample that Windows XP came with. I roughly converted to .mp4 and .mkv for additional test material. As the screen shot shows Kodi picks up on the gerbera serving of the .avi. I made no additional change to gerbera or Kodi.

**Comment by ringprince** [comment]
Thanks for looking into this and the fast response.  I am sorry for my rash report.  The problem seems not related to file type.  gerbera just exports only some of the files to upnp clients.  I have now also tested this with kodi.
Playing the files through the web interface works, but none of the clients sees the files.  
File permissions are the same on all files (exported and non-exported).

Is there some limit of exported items?

**Comment by Martii** [comment]
> Is there some limit of exported items?

File systems usually have some limitations especially in the root. I presume you are using ext4? I've had issues with over 80000 files *(the exact number is unknown but I suspect it's 32767 i.e. 32K files)* just in the OS alone, with Intel/AMD64, so those get to be sub-foldered to speed things up. Unsure about gerbera itself *(more aptly UPnP DLNA protocols I think)*. However I am serving to my network a little over 3000 media features/series in a little over 60 sub-folders. Not many are .avi but I have a few still.

I did test VLC and it picks up the .avi files under K/Ubuntu though in my host systems. So not entirely sure what's going on with Debian. Ubuntu is similar in distro so it should be nearly the same. Usually Debian is a bit more on the "stable" side and less bleeding edge like K/Ubuntu.

Are you missing any codecs for your AVI's? or some other subsystem specific to AVI? Although not sure that would really affect anything. My HEVC encoded containers show up on my appliances but don't play since they don't have that decode function.

At one point, a few times, I had to unshare and wipe the database and reshare the folders to get a specific version of gerbera to work well, with iNotify, but haven't had to do that for almost a year.

> ... armel ...

Haven't used an ARMel device architecture at all however in a general search the results claim it to be 32 bit. If this is the case you might have some file size limitations too with sharing regardless of the OS file system. So the 1.clock...avi didn't work for you either? That's like super old codecs that should be well supported in any distro/arch.

Since I'm not the expert here with gerbera I'll defer to the more experienced in the project but I can offer more on the systems analysis side, and prior limited, out of the box, gerbera... if that's where your issue lies.

**Comment by v00d00** [comment]
I assume the files show up in the UI?

**Comment by ringprince** [comment]
OK, I investigated further.  And I have to say sorry for the misleading bug report.

(Yes, all files were accessible through the web interface.)

I found these entries in the log file

    2019-08-11 13:04:51   ERROR: Inotify thread caught exception: The user limit on the total number of inotify watches was reached or the kernel failed to allocate a needed resource.
    Exception raised in [src/mt_inotify.cc:89] addWatch(): The user limit on the total number of inotify watches was reached or the kernel failed to allocate a needed resource.

I switched to timed updates for now.  After removing the directories from the database and re-adding them, all files are now exported to the clients.

**Comment by Martii** [comment]
@ringprince 

Hmm..

``` sh-session
$ cat /proc/sys/fs/inotify/max_user_watches
8192
```

What's yours set at? I've never touched the default here.

**Comment by v00d00** [comment]
Great, closing for now.
