### ISSUE TITLE
Correctly support multiple artists

### ISSUE THREAD

**Issue by cweiske** [gerbera/gerbera#70]
I have several albums with songs sung by multiple artists. The ogg and mp3 files have multiple artist fields.

In the "Artists" tree, entries named "artist1 artist2" are created instead of 2 artist entries that contain both the same songs.

Screenshot:

![2017-04-14 gerbera multiple artists](https://cloud.githubusercontent.com/assets/59036/25026593/721c6cb8-20a7-11e7-8d44-1fe1be554489.png)

Those with combined names are duets, the other ones have only one artist tag.

**Comment by v00d00** [comment]
Hey, are you using the JavaScript import method? What does your import.js look like

**Comment by cweiske** [comment]
Yes, javascript. I'm actually using the standard import.js file.

**Comment by basxto** [comment]
I’ve written a script for using the ARTISTS tag created by [picard](https://picard.musicbrainz.org/).
Maybe this could be added to `import.js` as an commented out alternative?

Getting the artist list (needs `<add-data tag="TXXX:ARTISTS"/>`)
```js
    var artist = obj.meta[M_ARTIST];
    if (!artist) {
        artist = 'Unknown';
        artist_full = null;
    } else {
        artist_full = artist;
        desc = artist;
    }

    var artists = obj.aux['TXXX:ARTISTS'];
    if (!artists)
        artists = [artist];
    else {
        //Workaround for pre1.6.0
        artists = artists.replace(/.*ARTISTS /g, '');
        artists = artists.replace(/ /g, '\n');
        artists = artists.replace(/(Various)\n(Artists)/i,'$1 $2').replace(/(Radical)\n(Redemption)/i,'$1 $2').replace(/(Rotterdam)\n(Terror)\n(Corps)/i,'$1 $2 $3').replace(/(Sub)\n(Zero)\n(Project)/i,'$1 $2 $3').replace(/(Menace)\n(II)\n(Society)/i,'$1 $2 $3');
        artists = artists.replace(/(^|\n)(tha|the|mc|dj|dr.|le)\n/gi,'$1$2 ');
        artists = artists.replace(/\n(of|for|&|by)\n/gi,' $1 ');
        artists = artists.split('\n');
    }

```
Building the structure
```js
    for(var i = 0; i < artists.length; ++i){
        chain = ['Audio', 'Artists', artists[i], 'All - full name'];
        addCdsObject(obj, createContainerChain(chain));

        chain = ['Audio', 'Artists', artists[i], album];
        obj.title = track + title;
        addCdsObject(obj, createContainerChain(chain), UPNP_CLASS_CONTAINER_MUSIC_ALBUM);
    }
```

I have a lot of tracks, which go like `40 Angerfist with DJ Outblast & MC tha Watcher - The Voice Of Mayhem.mp3` and this annoyed me for years, since no player gets it right. Remixes are even worse, since that’s often only mentioned in the title, but not in the author field.

**Comment by basxto** [comment]
I think this was also related to https://github.com/gerbera/gerbera/issues/759, since the space was used as a name seperator?

**Comment by ghlupe2** [comment]
Good to see that you found a solution for your use case. With performers it's a bit more complex. As a workaround I made a Picard tagging script:

```
$map(%_instruments%,$trim($performer(%_loop_value%) \(%_loop_value%\)))
$set(_id3:TXXX:Gerbera Performer List,%_instruments%)
```

For MP3 it generates a data tag
"TXXX:Gerbera Performer List" with a similar structure like in flac files, e.g. for the given sample file:

Ringo Starr (drums (drum set)); John Lennon, John Lennon (lead vocals); Ringo Starr (maracas); John Lennon (electric piano); Paul McCartney (electric bass guitar); George Harrison, John Lennon (electric guitar); John Lennon, Paul McCartney (background vocals); John Lennon (handclaps)

Which gives you the possibility to create an array of performers and their roles/instruments.

**Comment by ghlupe2** [comment]
Just gave it a try, for artists the Picard script would easily be

`$set(_id3:TXXX:Gerbera Artists,%artists%)`

and you could use TXXX:Gerbera Artists in your script using "; " as a separator for multiple artists. Same goes for Writer, Record Label and Release Type accordingly.

**Comment by basxto** [comment]
Is the role relevant for sorting it into artists?
But I noticed that I have to extend my script for remixers and probably more. I have to see which tags all get populated for my music.

**Comment by ghlupe2** [comment]
> Is the role relevant for sorting it into artists?

Not necessarily, roles are connected to the "performing artists" and part of the [advanced relationship tags](https://picard-docs.musicbrainz.org/en/variables/tags_advanced.html#advanced-relationship-tags) in MusicBrainz. For many albums they are not maintained at all in the database.

> I have to see which tags all get populated for my music.

I guess that you would consider the TIPL (involved people) tag, which is hard to work with in Gerbera due to the lack of separating characters. Luckily Picard provides some of this information as separate fields for scripting. I am using this tagging script for MP3 files:

```
$set(_id3:TXXX:Gerbera Producer,%producer%)
$set(_id3:TXXX:Gerbera Engineer,%engineer%)
$set(_id3:TXXX:Gerbera Mixer,%mixer%)
$set(_id3:TXXX:Gerbera Arranger,%arranger%)

```
Again, you need to activate in Picard the metadata option "use track relationships".

**Comment by basxto** [comment]
It looks like artists and remixer is all I need. And I only sort it into the remixer, if it’s present, since that’s usually the most important artist. But I see how this has to be handled completly different from genre to genre.
