### ISSUE TITLE
Support order by track number with multiple CDs

### ISSUE THREAD

**Issue by cweiske** [gerbera/gerbera#832]
I have two CDs of the same album, and Gerbera sorts the titles after track number without taking the CD number into account:

1. Track 1 (CD1)
1. Track 1 (CD2)
1. Track 2 (CD1)
1. Track 2 (CD2)
1. ..

It would be nice if Gerbera would use the CD number field to sort the tracks in the correct order:

1. Track 1 (CD1)
1. Track 2 (CD1)
1. Track 1 (CD2)
1. Track 2 (CD2)

(I'm seeing that problem on gerbera 1.3.0, but I looked at the master code and did not see any changes regarding that behavior)

----

A quick fix could be to store the track number as `$trackNumber + $cdNumber * 100`. That would not need another field in the database table.

----

Original track number support was made in 3e42e3c9388cc3db2820d15f507a13c4d59be729

**Comment by ghlupe2** [comment]
Disc number is not part of the [global media object](http://docs.gerbera.io/en/latest/scripting.html?highlight=track-number#general-properties). You can achieve this by using id3 [import options ](http://docs.gerbera.io/en/latest/config-import.html?highlight=auxdata#id3) and scripting. For mp3 it's TPOS and DISCNUMBER for flac.

**Comment by KarlStraussberger** [comment]
This is only useful on gerbera webpage and if we handle disk number in track number sorts (like suggested in the quick fix) because there is no protocol item to request track number sorting.

There is an unused field `sortPriority` in `CdsObject` (not stored in DB either) which might be used for carring the result after adding it to the database.

To make it more flexible configuration should define a list of internal properties which are mangled into `sortPriority` like the above formula. Everything executed on import.

Finally, we need to extend the `add-data` configuration item to map it to our internal property depending on media type.

**Comment by whyman** [comment]
This shouldbe the default behaviour, we should not make people script for this as its such a common and sensible thing.

**Comment by cweiske** [comment]
Thank you!
