### ISSUE TITLE
Cache for thumbnails doesn't work

### ISSUE THREAD

**Issue by whitesnake-pl** [gerbera/gerbera#861]
I'm using Gerbera 1.5 (but checked this also with git-master 2020.05.13) on Archlinux.
Application doesn't store generated thumbnails in cache location. Cache location is not even created. If I create "cache-dir" by myself it doesn't change anything.
Thus, everytime I restart gerbera it keeps creating the thumbnails on demand. It doesn't use cache.

Once debug is enabled I see only
"Generating thumbnail for file: XXX" messages but no "Returning cached thumbnail for file: XXX" messages.

The folowing files are only visible in home/cache folder.
```
[root@myserver gerbera]# pwd
/var/lib/gerbera
[root@myserver gerbera]# ls -al
total 12780
drwxr-x---  2 gerbera gerbera     4096 May 13 11:49 .
drwxr-xr-x 35 root    root        4096 May 13 11:36 ..
-rw-r--r--  1 gerbera gerbera 12840960 May 13 12:03 gerbera.db
-rw-r--r--  1 gerbera gerbera   226232 May 13 12:03 gerbera.db-journal
-rw-r--r--  1 gerbera gerbera      127 May 13 11:43 gerbera.html
```

My configuration is as follows
```
    <name>MyGerbera</name>
    <udn>uuid:91d4053a-c73b-4f25-a14c-fb049ae851e5</udn>
    <home>/var/lib/gerbera</home>
    <webroot>/usr/share/gerbera/web</webroot>
    <protocolInfo extend="yes"/>
    <alive>1800</alive>
    <storage>
      <sqlite3 enabled="yes">
        <database-file>gerbera.db</database-file>
      </sqlite3>
    </storage>
    <extended-runtime-options>
      <ffmpegthumbnailer enabled="yes">
        <cache-dir enabled="yes"></cache-dir>
        <thumbnail-size>320</thumbnail-size>
        <seek-percentage>5</seek-percentage>
        <filmstrip-overlay>no</filmstrip-overlay>
        <workaround-bugs>no</workaround-bugs>
        <image-quality>8</image-quality>
      </ffmpegthumbnailer>
      <mark-played-items enabled="no" suppress-cds-updates="yes">
        <string mode="prepend">*</string>
        <mark>
          <content>video</content>
        </mark>
      </mark-played-items>
    </extended-runtime-options>
```

**Comment by whyman** [comment]
Thanks for reporting, can you post the debug log?

**Comment by whitesnake-pl** [comment]
Will post it later today. 

However, there is another strange behavior which I observed. Normally, gerbara is run under gerbera:gerbera privileges.
The folders which I have added for monitoring (using inode) they are with different privileges. Gerbera still can read them as the files and folders are o+rx.
However, since I was thinking once this might the a privilege issue I ran the gerbera with root:root privileges.
In consequence application in every folder which I added created for every single file folder with the name of the file + "-thumb.jpg". The folders are empty.
I guess this might be a bug then instead of creating thumbnails in /var/lib/gerbera/cache-dir it creates a folder?! in every file location.

**Comment by whitesnake-pl** [comment]
OK, just quickly checked the source code.

ffmpeg_handler.cc
```
    cache_dir = cache_dir / (movie_filename.string() + "-thumb.jpg");

    std::error_code ec;
    if (create && !fs::create_directories(cache_dir, ec))
        cache_dir = "";

```
Isn't it that case?

**Comment by whyman** [comment]
My _guess_ would be cache_dir was set as nullptr in a previous life, but got changed when we changed the string type to empty string resulting in this.

That code needs refactoring a bit it seems. PRs welcome!

**Comment by ytimenkov** [comment]
I'm working on a fix, let see if I finish it this week.

Problem is that path for jpg in cache got severely broken during transition to `fs::path`.

First instead of concatenating it just replaces cache base dir (documented behavior) with full path to video, then instead of file creates directory (what `create_directories` does)...

These are findings so far...

**Comment by whitesnake-pl** [comment]
Thank you. Fix solved the problem.
However, I can't see that the thumbnails are being created for images/pictures (videos are fine now). @ytimenkov can this be corrected as well?

**Comment by ytimenkov** [comment]
@whitesnake-pl 

No, I didn't touch the logic which generates thumbnails themselves.

Code says: `    if (config->getBoolOption(CFG_SERVER_EXTOPTS_FFMPEGTHUMBNAILER_ENABLED) && (startswith(item->getMimeType(), "video") || item->getFlag(OBJECT_FLAG_OGG_THEORA))) {
`
Which means only thumbnails for video files.

I've checked the code once again and it feels that "thumbnail logic" is implemented just as a hack inside normal information flow: instead of making a decision during scanning for metadata nad registering it in the DB, thumbnail resource is added to the item *during XML generation* (and completely bypasses DB).

Well, it's a rant for #875. I know nothing about ffmpeg thumbnailer and whether it is able to generate previews for images. This probably is a separate feature request.
