### ISSUE TITLE
1.5.0: Transcoding: Playback ends before file is complete

### ISSUE THREAD

**Issue by ectotropic** [gerbera/gerbera#917]
New issue since moving to 1.5.0 recently, where when transcoding the playback of files ends before the file is actually finished. Prior to this version things worked perfectly.

Log file of the relevant section attached, with debug info enabled. (I've trimmed it down to just the relevant parts).

Best I can figure the transcoder is killed before it has actually finished transcoding, and the amount of file that is left unplayed is related to the buffer size set for transcoding.

System is Ubuntu 20.04 (also a recent update, and potentially related?), and compiling gerbera from source (using the 1.5.0 release tag), and compiling the associated requirements too) 

Transcoding is done via a shell script which (using exec) runs a perl script which deals with the actual transcoding - the output logs from those indicate the shell script is always terminated by gebera before the script has completed. I tried editing the buffer size and it seems to change when the playback stops - as does changing what transcoding does (i.e. remuxing only seems to cause earlier stops than actually transcoding). Either of those may be red-herrings though.

Had a look at the source, but following the chain of events that leads to a 'kill' command is not easy - normally I'd stick a breakpoint in, but doing remote linux debugging is not something I know anything about.

My hunch is that there's something happening with the FIFO and/or buffering where it's stopping serving the file *after* the transcoder has closed the pipe, but *before* the pipe data has all been sent to the device. Although I could easily be wrong! Whatever is happening, the transcoding script, is *always* killed before it has exited completely (although I think it's probably in the process of doing so when it is killed).

Sadly, it's a huge time-sink to test this for me, so although I'm happy to provide extra information as need be, I may not be able to run many test on this.

[gerbera_edit.log](https://github.com/gerbera/gerbera/files/4787170/gerbera_edit.log)

**Comment by ectotropic** [comment]
Finally managed to verify that this is also an issue with the latest developement version, and also does seem to be related to buffer size: larger the buffer, the more of a file is truncated.

**Comment by ectotropic** [comment]
More info: seems that it's actually truncating **both** ends of the file when transcoding. The truncation of the start of the file seems not related to the buffer size, but the first section of the video definitely does not show - missed this earlier because it's a pretty short skip and with most files I have it doesn't actually matter (it's just a lead-in pre-roll thing). If the transcoding buffer is small this is similar to how the end of files are truncated: it's pretty easy to miss as it is mostly not anything relevant (credits, etc.).

**Comment by whyman** [comment]
Interesting, sounds almost like an off by one to me...

**Comment by dyseg** [comment]
Issue is still present in current master build. I found two problems:
* content type was not set as "chuncked". See fix: https://github.com/gerbera/gerbera/commit/bc59e4b00c9fdf55db094e419ec44cdae8232f62 and the corresponding pupnp code: https://github.com/pupnp/pupnp/blob/d1247f083cf01f1774615c020e80cb6233c4d6eb/upnp/src/genlib/net/http/webserver.c#L1310-L1323
There is a configurable option `<use-chunked-encoding>yes</use-chunked-encoding>`, but I did not found any source code which was different based on this option(correct me if I'm wrong)
* if we read 0 bytes from the transcoding fifo, and the transcoding process is still running we return -1, which is interpreted as `read error` and the media playback is interrupted. https://github.com/gerbera/gerbera/blob/f3182bc8781392b98596281d5574998106682c43/src/iohandler/process_io_handler.cc#L243-L261
Completely removing this part I think makes sense, because we would still catch a read error here:
https://github.com/gerbera/gerbera/blob/f3182bc8781392b98596281d5574998106682c43/src/iohandler/process_io_handler.cc#L228-L231
and reading 0 bytes means `feof` anyway:
```
/* Read NBYTES into BUF from FD.  Return the
   number read, -1 for errors or 0 for EOF.

   This function is a cancellation point and therefore not marked with
   __THROW.  */
extern ssize_t read (int __fd, void *__buf, size_t __nbytes) __wur;
```

@whyman please se my changes here: https://github.com/gerbera/gerbera/compare/master...dyseg:fix_tr and share your thoughts!

**Comment by whyman** [comment]
@dyseg sounds sensible

**Comment by whyman** [comment]
@dyseg Can you open a PR?

**Comment by dyseg** [comment]
@whyman Should I also remove the ATTR_TRANSCODING_PROFILES_PROFLE_USECHUNKEDENC config option? It is not used for anything.

**Comment by KarlStraussberger** [comment]
> @whyman Should I also remove the ATTR_TRANSCODING_PROFILES_PROFLE_USECHUNKEDENC config option? It is not used for anything.

If it's not used, drop it. We love to leave no one behind :smile:
